server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
	# To serve unencrypted traffic on port 80:
	#root /srv/www/html;
	#include php[.]conf;
	# By default, let's redirect to https -- with an exception for
	# the ACME challenge which by definition can't run over HTTPS
	location /.well-known/acme-challenge/ {
		root /srv/www/html;
		auth_basic off;
		allow all;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}

server {
	listen 443 default_server ssl;
	listen [::]:443 default_server ssl;
	http2 on;

	listen 443 quic;
	listen [::]:443 quic;
	add_header Alt-Svc 'h3=":443"; ma=86400';
	server_name _;

	ssl_certificate /etc/pki/tls/certs/nginx.pem;
	ssl_certificate_key /etc/pki/tls/private/nginx.pem;
	keepalive_timeout 70;
	include ssl[.]conf;

	root /srv/www/html;
	# Support php if we have it
	include php[.]conf;
}
