include /usr/share/nginx/modules/*[.]conf;
worker_processes auto;

# For global configuration
include /etc/nginx/conf.d/*[.]conf;

events {
	worker_connections 1024;
}

http {
	include mime.types;
	default_type application/octet-stream;

	brotli on;
	brotli_static on;
	brotli_comp_level 6;
	brotli_min_length 20;
	brotli_types
		application/atom+xml
		application/xhtml+xml
		application/xspf+xml
		application/javascript
		application/json
		application/rss+xml
		application/xml
		application/x-perl
		application/x-tcl
		application/wasm
		image/svg+xml
		image/x-icon
		text/css
		text/plain
		text/mathml
		text/x-c
		text/x-c++
		text/x-chdr
		text/x-c++hdr
		text/x-python
		text/x-shellscript
		text/vnd.wap.wml
		text/x-component
		font/ttf
		font/otf
		application/vnd.ms-fontobject
		application/x-font-ttf
		application/x-font-opentype
		application/vnd.apple.mpegurl;

	# gzip fallback for non-brotli browsers
	gzip on;
	gzip_static on;
	gzip_comp_level 5;
	gzip_types
		application/atom+xml
		application/xhtml+xml
		application/xspf+xml
		application/javascript
		application/json
		application/rss+xml
		application/xml
		application/x-perl
		application/x-tcl
		application/wasm
		image/svg+xml
		image/x-icon
		text/css
		text/plain
		text/mathml
		text/x-c
		text/x-c++
		text/x-chdr
		text/x-c++hdr
		text/x-python
		text/x-shellscript
		text/vnd.wap.wml
		text/x-component
		font/ttf
		font/otf
		application/vnd.ms-fontobject
		application/x-font-ttf
		application/x-font-opentype
		application/vnd.apple.mpegurl;

	sendfile on;
	keepalive_timeout 65;

	# http configuration affecting all sites, e.g.
	# setting an upstream for php handling
	include /etc/nginx/http.conf.d/*[.]conf;

	include /etc/nginx/sites-enabled/*;
}
