include /usr/share/nginx/modules/*[.]conf;
worker_processes auto;

# For global configuration
include /etc/nginx/conf.d/*[.]conf;

events {
	worker_connections 1024;
}

http {
	include mime.types;
	default_type application/octet-stream;

	include /etc/nginx/realip[.]conf;

	# Static compression is always beneficial
	brotli_static on;
	gzip_static on;
	# Dynamic compression is in an optional file
	# so it can be disabled/deleted easily if another
	# component (e.g. traefik) handles on-the-fly
	# compression
	include /etc/nginx/compression[.]conf;

	sendfile on;
	keepalive_timeout 65;

	# http configuration affecting all sites, e.g.
	# setting an upstream for php handling
	include /etc/nginx/http.conf.d/*[.]conf;

	include /etc/nginx/sites-enabled/*;
}
