# If we're running behind Traefik on 127.0.0.1/::1, let the
# rest of the stack know the real IP
set_real_ip_from 127.0.0.1;
set_real_ip_from ::1;
real_ip_header X-Forwarded-For;
real_ip_recursive on;
